apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  ports:
    - port: 9042
      name: cql
    - port: 7199
      name: jmx
  selector:
    name: cassandra
