apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  replicas: 3
  selector:
    name: cassandra
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
        - image: dcparker88/cassandra:latest
          name: cassandra
          env:
            - name: PEER_DISCOVERY_SERVICE
              value: cassandra-peers
            # Feel free to change the following:
            - name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - name: CASSANDRA_DC
              value: DC1
            - name: CASSANDRA_RACK
              value: Kubernetes Cluster
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          resources:
            limits:
              cpu: "4"
              memory: 10Gi
            requests:
             cpu: "4"
             memory: 10Gi
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - nodetool decommission
          terminationGracePeriodSeconds: 300
          ports:
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: data
      volumes:
        - name: data
          emptyDir: {}
