apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra-nodeport
  name: cassandra-nodeport
spec:
  ports:
  - name: cql
    nodePort: 30700
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    name: cassandra
  type: NodePort
